export const students = [
  {
    id: 1,
    name: "Ramdasani Mahek Kamal ",
    email: "mahekramdasani@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 2,
    name: "Gadhvi Bansi Mayurdan ",
    email: "bansigadhvi1410@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 3,
    name: "Naira Doctor ",
    email: "2021002170610005@ljku.edu.in",
    type: "participant",
    isActive: true,
  },
  {
    id: 4,
    name: "Raj Shah",
    email: "rajshahthegreatscientist@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 5,
    name: "Mohit Kamal Ramdasani ",
    email: "mohitramdasani531@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 6,
    name: "SIDDH DIVYESH SHAH",
    email: "shahsiddh08@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 7,
    name: "VINIT HARISHBHAI CHOKSHI",
    email: "vinitchokshi1809@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 8,
    name: "SUTHAR KRISH ASHVINBHAI",
    email: "krishsutharofficial@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 9,
    name: "Parthiv Patel",
    email: "pparthiv077@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 10,
    name: "Aamirkhan Pathan ",
    email: "pathanaamirkhan237@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 11,
    name: "Tirth Ajaykumar Patel",
    email: "tirthajay6@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 12,
    name: "Makwana Abhishek",
    email: "abhishekmakwana7021@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 13,
    name: "Ishita Swami",
    email: "ishitaswami21@cse.iiitp.ac.in",
    type: "participant",
    isActive: true,
  },
  {
    id: 14,
    name: "Kushal Badal ",
    email: "badalkushal999@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 15,
    name: "Panchal Ansh Vijay",
    email: "avp346710@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 16,
    name: "Dharmik Patel",
    email: "dharmikpatel7112@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 17,
    name: "Vishwa Raval ",
    email: "vishwaraval247@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 18,
    name: "Perin Modi",
    email: "modiperin@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 19,
    name: "Shubham Dineshkumar Prajapati",
    email: "shubhamdp.255@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 20,
    name: "Bhagya Shah",
    email: "bhagyashah5122002@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 21,
    name: "Shah Kavisha ",
    email: "shahkavi02@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 22,
    name: "Neeraja Buch",
    email: "neeraja0093@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 23,
    name: "Dhruvi soni",
    email: "sonidhruvi2003@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 24,
    name: "Harsh Dobariya ",
    email: "harshdobariya79@gmail.com",
    type: "3rd",
    isActive: true,
  },
  {
    id: 25,
    name: "Shubham Thanki ",
    email: "shubhamthanky@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 26,
    name: "Harsh Hemal Bhatt",
    email: "harsh.bhatt811@gmail.com",
    type: "1st",
    isActive: true,
  },
  {
    id: 27,
    name: "Samarth Patel",
    email: "190320107080.ce.samarth.patel@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 28,
    name: "Henil Shantilal Suhagiya ",
    email: "henilsuhagiya0@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 29,
    name: "Shah kunj Rajeshbhai ",
    email: "shahkunj2003@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 30,
    name: "Patel Dhairya Lalitkumar ",
    email: "pateldhairya0210@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 31,
    name: "Maulik malani",
    email: "maulikmalani40@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 32,
    name: "Mansi parmar",
    email: "mansirp129@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 33,
    name: "VRAJ PATEL",
    email: "patelvraju07@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 34,
    name: "Mansi parmar",
    email: "mansirp129@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 35,
    name: "Gajera Harvi Varishbhai",
    email: "harvigajera@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 36,
    name: "Meshva Himanshu Patel ",
    email: "meshva2003@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 37,
    name: "Bhavika Gehani ",
    email: "bhavikabhavi188@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 38,
    name: "shreeji prafulbhai parmar",
    email: "shreeji773@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 39,
    name: "Rahul dabhi vinodkumar",
    email: "rvdabhi2002@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 40,
    name: "Vidhi chetanbhai vamja ",
    email: "Vidhivamja8@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 41,
    name: "Deep Sheth",
    email: "shethdeep12@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 42,
    name: "Vidhi chetanbhai vamja ",
    email: "Vidhivamja8@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 43,
    name: "Aaliya Asfak Rangoonwala",
    email: "aaliyar2003@gmail.con",
    type: "participant",
    isActive: true,
  },
  {
    id: 44,
    name: "Darshi Ketanbhai Pujara ",
    email: "darshipujara90@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 45,
    name: "Princekumar Pravinbhai Vanani",
    email: "vananiprince820@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 46,
    name: "Shah Heli Dipenbhai ",
    email: "dipenshah1829@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 47,
    name: "nishit mistry ",
    email: "nishitmistry94@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 48,
    name: "Het sojitra ",
    email: "het.sojitra4399@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 49,
    name: "Dev Bhavsar",
    email: "dbhavsar154@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 50,
    name: "Yash Patel",
    email: "yashpatel45273@gmail.com",
    type: "2nd",
    isActive: true,
  },
  {
    id: 51,
    name: "Dodiya Pruthvirajsinh Vikramsinh ",
    email: "pruthvidodiya99@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 52,
    name: "Modi Dhruvil Atulkumar",
    email: "dhruvilmodi2503@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 53,
    name: "Sakshi Raval ",
    email: "sakshi.raval01@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 54,
    name: "Vidit Gandhi",
    email: "vidit.21102@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 55,
    name: "Tulja patel ",
    email: "pateltulja734@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 56,
    name: "Pitroda krish kalpeshbhai ",
    email: "krishpitroda08@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 57,
    name: "Dhairya Morbiya ",
    email: "190320132013.ict.dhairya.morbiya@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 58,
    name: "Lara Makwana",
    email: "laramak2509@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 59,
    name: "Sahil Nitinkumar Patel",
    email: "sahilp14323@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 60,
    name: "yashvi shripalbhai palkhiwala",
    email: "yashvipalkhiwala2401@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 61,
    name: "Patel Vidhi Mukeshkumar ",
    email: "2021002171210129@ljku.edu.in",
    type: "participant",
    isActive: true,
  },
  {
    id: 62,
    name: "Anusha Jotwani ",
    email: "anusha.jotwani@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 63,
    name: "Sneh Bhupendrabhai Patel",
    email: "sneh.patel2012@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 64,
    name: "Parth Patel ",
    email: "parthpatel06072004@gmail.com",
    type: "participant",
    isActive: true,
  },
  {
    id: 65,
    name: "Shivam Tripathi",
    email: "spt3009@gmail.com",
    type: "participant",
    isActive: true,
  },
  /* Co-Ordinators */
  {
    id: 66,
    email: "",
    name: "Fagun Doshi",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 69,
    email: "",
    name: "Vivek Thobhani",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 70,
    email: "",
    name: "Kaiwal Panchal",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 72,
    email: "",
    name: "Devanshu Shah",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 73,
    email: "",
    name: "Kriyanshi shah",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 74,
    email: "",
    name: "Dhrumin Mittal",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 75,
    email: "",
    name: "Eshika Jagani",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 76,
    email: "",
    name: "Yagna Patel",
    type: "co-ordinator",
    isActive: true,
  },
];